2025-03-04 23:17:44,638 - INFO - üîç Starting system check...
2025-03-04 23:17:44,702 - WARNING - ‚ö†Ô∏è Recommended Upgrade: NVIDIA A100
2025-03-04 23:17:44,703 - WARNING - ‚ö†Ô∏è Recommended Upgrade: NVIDIA A100
2025-03-04 23:17:44,703 - WARNING - ‚ö†Ô∏è Recommended Upgrade: NVIDIA A100
2025-03-04 23:17:44,704 - WARNING - ‚ö†Ô∏è Recommended Upgrade: NVIDIA A100
2025-03-04 23:17:44,704 - WARNING - ‚ö†Ô∏è Recommended Upgrade: NVIDIA A100
2025-03-04 23:17:44,705 - WARNING - ‚ö†Ô∏è Recommended Upgrade: NVIDIA A100
2025-03-04 23:17:44,705 - WARNING - ‚ö†Ô∏è Recommended Upgrade: NVIDIA A100
2025-03-04 23:17:44,705 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "check_system_ex.py", line 22, in <module>
    checker.run_all_checks()
  File "/caefs/user/mmingyeong/structura/Structura/src/system_checker.py", line 97, in run_all_checks
    self.check_config_file()
AttributeError: 'SystemChecker' object has no attribute 'check_config_file'
