2025-04-21 21:15:36,217 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/density_kde_seq_chunks/00_TestDensity.py", line 199, in <module>
    warm_calc.calculate_density_map(kernel=kernel_func, h=bandwidth, use_lut=use_lut)
  File "/caefs/user/mmingyeong/structura/Structura/src/density.py", line 331, in calculate_density_map
    _pcd_triangular(self.particles, density_map,
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/numba/core/dispatcher.py", line 424, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/numba/core/dispatcher.py", line 365, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name '_apply_periodic': Cannot determine Numba type of <class 'function'>

File "../../density.py", line 195:
    def _pcd_triangular(
        <source elided>
                for ix in range(ix_min, ix_max + 1):
                    dx = _apply_periodic(x_centers[ix] - px, half_x, box_x)
                    ^

During: Pass nopython_type_inference
