2025-03-08 12:51:18,113 - INFO - GPU is available. CuPy will be used for FFT.
2025-03-08 12:51:18,860 - INFO - Using GPU device 1.
2025-03-08 12:51:18,861 - INFO - Output directory 'TNG300_ICS' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-08 12:51:18,861 - INFO - Output directory 'TNG300_snapshot99' is set to: /caefs/data/IllustrisTNG/snapshot-99-dm-npy/cache
2025-03-08 12:51:18,861 - WARNING - Output directory 'NPZ' does not exist: /path/to/your/output/npz
2025-03-08 12:51:18,861 - INFO - Output directory 'NPY' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-08 12:51:18,861 - WARNING - Output directory 'LOGS' does not exist: /path/to/your/logs
2025-03-08 12:51:18,861 - INFO - Snapshot99 데이터 폴더: /caefs/data/IllustrisTNG/snapshot-99-dm-npy/cache
2025-03-08 12:51:18,862 - INFO - Output directory: /caefs/user/mmingyeong/structura/Structura/src/results
2025-03-08 12:51:18,862 - INFO - 전체 Snapshot99 데이터를 로드합니다...
2025-03-08 13:17:26,497 - INFO - Time elapsed for loading all data chunks: 1567.63 seconds
2025-03-08 13:17:26,502 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/fft_kde_ex.py", line 96, in <module>
    main()
  File "/caefs/user/mmingyeong/structura/Structura/src/example/fft_kde_ex.py", line 35, in main
    positions = loader.load_all_chunks(sampling_rate=1)
  File "/caefs/user/mmingyeong/structura/Structura/src/data_loader.py", line 175, in load_all_chunks
    combined_np = np.vstack(
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 348. GiB for an array with shape (15573227461, 3) and data type float64
