2025-03-05 20:35:33,226 - INFO - ✅ Using GPU device 1.
2025-03-05 20:35:33,227 - WARNING - ⚠️ Output directory 'NPZ' does not exist: /path/to/your/output/npz
2025-03-05 20:35:33,228 - INFO - 📁 Output directory 'NPY' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-05 20:35:33,228 - WARNING - ⚠️ Output directory 'LOGS' does not exist: /path/to/your/logs
2025-03-05 20:35:33,329 - INFO - 📁 Input (npy) folder: /caefs/data/IllustrisTNG/300/ICS
2025-03-05 20:35:33,329 - INFO - 📁 Output folder: /caefs/user/mmingyeong/structura/Structura/src/results
2025-03-05 20:35:33,331 - INFO - 📂 Detected 313 .npy files in the input folder.
2025-03-05 20:35:33,331 - INFO - 📄 Example file: chunk_89.npy
2025-03-05 20:35:33,331 - INFO - ✅ X range set: 64358.89 - 71133.51 ckpc/h (Center: 100 cMpc/h, Thickness: 10 cMpc/h)
2025-03-05 20:35:33,331 - INFO - 🔹 Filtering X range: 64358.89 - 71133.51 ckpc/h (64.359 - 71.134 cMpc/h)
2025-03-05 20:35:33,331 - INFO - 🔹 Loading data...
2025-03-05 20:36:25,072 - INFO - ✅ Time taken to load all chunks: 51.74s
2025-03-05 20:36:25,187 - INFO - ✅ Data loaded successfully. Shape: (516132, 3)
2025-03-05 20:36:25,187 - INFO - 🔹 Computing 2D histogram and generating image plot...
2025-03-05 20:36:25,563 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/visualization_ex.py", line 74, in <module>
    saved_files = viz.create_image_plot(
  File "/caefs/user/mmingyeong/structura/Structura/src/visualization.py", line 172, in create_image_plot
    if additional_info:
NameError: name 'additional_info' is not defined
